In [1]:
import pandas as pd

# Crop yield data (kg per hectare)
crop_yield = pd.Series([3200, 2800, 3500, 3000],
                       index=["Wheat", "Rice", "Maize", "Millet"])

crop_yield

Wheat     3200
Rice      2800
Maize     3500
Millet    3000
dtype: int64

In [2]:
crop_yield["Rice"]

np.int64(2800)

In [3]:
crop_yield.iloc[2]

np.int64(3500)

In [4]:
crop_yield.idxmax()

'Maize'

In [5]:
improved_yield = crop_yield * 1.05
improved_yield

Wheat     3360.0
Rice      2940.0
Maize     3675.0
Millet    3150.0
dtype: float64

In [6]:
import pandas as pd

# Crop yield data (kg per hectare)
crop_yield = pd.Series([2100, 3800, 1500, 1900],
                       index=["Wheat", "Rice", "Maize", "Millet"])

crop_yield

Wheat     2100
Rice      3800
Maize     1500
Millet    1900
dtype: int64

In [7]:
crop_yield["Rice"]

np.int64(3800)

In [8]:
crop_yield.iloc[2]

np.int64(1500)

In [9]:
crop_yield.idxmax()

'Rice'

In [10]:
improved_yield = crop_yield * 1.05
improved_yield

Wheat     2205.0
Rice      3990.0
Maize     1575.0
Millet    1995.0
dtype: float64